import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "data" / "games.json"
INDEX_PATH = ROOT / "index.html"
GAME_DIR = ROOT / "games" / "corebound"


class CoreboundArcadeReleaseTests(unittest.TestCase):
    def test_manifest_registers_playable_corebound_release(self) -> None:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        games = manifest.get("games")

        self.assertIsInstance(games, list)
        corebound = next((game for game in games if game.get("slug") == "corebound"), None)
        self.assertIsNotNone(corebound)
        self.assertEqual("Corebound", corebound["title"])
        self.assertEqual("0.7.0", corebound["version"])
        self.assertEqual("playable", corebound["status"])
        self.assertEqual("games/corebound/", corebound["path"])
        self.assertIn("Mantis-01", corebound["summary"])
        self.assertIn("compact overlay HUD", corebound["summary"])
        self.assertIn("keyboard and touch menu surfaces", corebound["summary"])
        self.assertIn("surface dock services", corebound["summary"])
        self.assertIn("richer material strata", corebound["summary"])
        self.assertIn("embedded ore and hazard pockets", corebound["summary"])
        self.assertIn("smooth drill breakthrough feedback", corebound["summary"])
        self.assertIn("contracts", corebound["summary"])
        self.assertIn("archives", corebound["summary"])
        self.assertIn("Deep Charters", corebound["summary"])
        self.assertIn("late routes", corebound["summary"])
        self.assertIn("v0.7.0 HUD Breakthrough", corebound["release"]["label"])
        self.assertIn("compressed overlay", corebound["release"]["copy"])
        self.assertIn("shared menu surface", corebound["release"]["copy"])
        self.assertIn("surface dock", corebound["release"]["copy"])
        self.assertIn("enriches strata", corebound["release"]["copy"])
        self.assertIn("continuous breakthrough motion", corebound["release"]["copy"])
        self.assertIn("cell-center snap", corebound["release"]["copy"])
        self.assertTrue((GAME_DIR / "index.html").is_file())
        self.assertTrue((GAME_DIR / "corebound.js").is_file())
        self.assertTrue((GAME_DIR / "corebound-data.js").is_file())

    def test_manifest_documents_commit_backed_snapshot(self) -> None:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        corebound = next(game for game in manifest["games"] if game.get("slug") == "corebound")
        versions = corebound.get("versions")

        self.assertNotIn("snapshot", corebound)
        self.assertIsInstance(versions, list)
        self.assertEqual("0.7.0", versions[0]["version"])
        self.assertEqual("games/corebound/versions/0.7.0/", versions[0]["path"])
        self.assertEqual("2026-04-28", versions[0]["releasedAt"])
        self.assertEqual("v0.7.0 HUD Breakthrough", versions[0]["label"])
        self.assertIn("Compact overlay HUD", versions[0]["summary"])
        self.assertIn("surface dock services", versions[0]["summary"])
        self.assertIn("richer strata", versions[0]["summary"])
        self.assertIn("embedded ore and hazard pockets", versions[0]["summary"])
        self.assertIn("smooth breakthrough release motion", versions[0]["summary"])
        self.assertTrue(versions[0]["commit"].startswith("db07d9e"))
        self.assertEqual("0.6.0", versions[1]["version"])
        self.assertEqual("games/corebound/versions/0.6.0/", versions[1]["path"])
        self.assertEqual("0.5.0", versions[2]["version"])
        self.assertEqual("games/corebound/versions/0.5.0/", versions[2]["path"])
        self.assertEqual("0.4.0", versions[3]["version"])
        self.assertEqual("games/corebound/versions/0.4.0/", versions[3]["path"])
        self.assertEqual("0.3.0", versions[4]["version"])
        self.assertEqual("games/corebound/versions/0.3.0/", versions[4]["path"])
        self.assertEqual("0.2.0", versions[5]["version"])
        self.assertEqual("games/corebound/versions/0.2.0/", versions[5]["path"])
        self.assertTrue((GAME_DIR / "versions" / "0.7.0" / "index.html").is_file())
        self.assertTrue((GAME_DIR / "versions" / "0.6.0" / "index.html").is_file())
        self.assertTrue((GAME_DIR / "versions" / "0.5.0" / "index.html").is_file())
        self.assertTrue((GAME_DIR / "versions" / "0.4.0" / "index.html").is_file())
        self.assertTrue((GAME_DIR / "versions" / "0.3.0" / "index.html").is_file())
        self.assertTrue((GAME_DIR / "versions" / "0.2.0" / "index.html").is_file())

    def test_corebound_snapshot_contains_hud_breakthrough_material_menu_and_assets(self) -> None:
        snapshot_dir = GAME_DIR / "versions" / "0.7.0"
        snapshot_html = (snapshot_dir / "index.html").read_text(encoding="utf-8")
        snapshot_data = (snapshot_dir / "corebound-data.js").read_text(encoding="utf-8")
        snapshot_script = (snapshot_dir / "corebound.js").read_text(encoding="utf-8")
        snapshot_css = (snapshot_dir / "corebound.css").read_text(encoding="utf-8")
        snapshot_manifest = json.loads((snapshot_dir / "assets" / "asset-manifest.json").read_text(encoding="utf-8"))

        self.assertIn("Open Corebound menu and help", snapshot_html)
        self.assertIn("class=\"hud in-game-hud\"", snapshot_html)
        self.assertIn("class=\"objective-panel objective-chip\"", snapshot_html)
        self.assertIn("class=\"surface-panel surface-dock\"", snapshot_html)
        self.assertIn("class=\"help-surface menu-surface\"", snapshot_html)
        self.assertIn("class=\"control-pad\"", snapshot_html)
        self.assertIn("help-quick-start", snapshot_html)
        self.assertIn("help-reset-run", snapshot_html)
        self.assertIn("Deep Charter", snapshot_html)
        self.assertIn("Late Route", snapshot_html)
        self.assertIn('src="assets/surface/surface-facilities-panel.png"', snapshot_html)
        self.assertIn('version: "v0.7.0"', snapshot_data)
        self.assertIn('snapshot: "HUD Breakthrough release"', snapshot_data)
        self.assertIn("drillContact:", snapshot_data)
        self.assertIn("hardnessSeconds:", snapshot_data)
        self.assertIn("drillPower: 1", snapshot_data)
        self.assertIn("motion:", snapshot_data)
        self.assertIn("materialRendering:", snapshot_data)
        self.assertIn("terrainMaterials:", snapshot_data)
        self.assertIn("oreDeposits:", snapshot_data)
        self.assertIn("hazardInclusions:", snapshot_data)
        self.assertIn("sourceManifest: \"assets/asset-manifest.json\"", snapshot_data)
        self.assertIn("\"rig.mantis_motion_strip\"", snapshot_data)
        self.assertIn("\"terrain.loam_gritstone_tile\"", snapshot_data)
        self.assertIn("\"upgrades.research_atlas\"", snapshot_data)
        self.assertIn("iconSlot:", snapshot_data)
        self.assertIn("rigModule:", snapshot_data)
        self.assertIn("deepCharters", snapshot_data)
        self.assertIn("routePlans", snapshot_data)
        self.assertIn("choirSlate", snapshot_data)
        self.assertIn("anchorRecall", snapshot_data)
        self.assertIn("startDrillContact", snapshot_script)
        self.assertIn("advanceDrillContact", snapshot_script)
        self.assertIn("drawDrillContactFeedback", snapshot_script)
        self.assertIn("startBreakthroughRelease", snapshot_script)
        self.assertIn("updateBreakthroughRelease", snapshot_script)
        self.assertIn("drawBreakthroughReleaseWake", snapshot_script)
        self.assertIn("setPostBreakMotion", snapshot_script)
        self.assertIn("ONBOARDING_STEPS", snapshot_script)
        self.assertIn("renderHelpSurface", snapshot_script)
        self.assertIn("contractsLayerOpen", snapshot_script)
        self.assertIn("updateMotion(dt)", snapshot_script)
        self.assertIn("cellFromMotion", snapshot_script)
        self.assertIn("drawMaterialBridge", snapshot_script)
        self.assertIn("drawEmbeddedOreDeposit", snapshot_script)
        self.assertIn("drawEmbeddedHazardPocket", snapshot_script)
        self.assertIn("cameraMaterialShake", snapshot_script)
        self.assertIn("loadAssetImages", snapshot_script)
        self.assertIn("drawRigFeedback", snapshot_script)
        self.assertIn("acceptCharter", snapshot_script)
        self.assertIn("selectRoutePlan", snapshot_script)
        self.assertIn("grid-template-columns: repeat(6, minmax(0, 1fr));", snapshot_css)
        self.assertIn("max-height: 1.2em;", snapshot_css)
        self.assertEqual(9, len(snapshot_manifest["assets"]))
        for asset in snapshot_manifest["assets"]:
            self.assertTrue((snapshot_dir / asset["path"].removeprefix("games/corebound/")).is_file())

    def test_generated_arcade_links_to_corebound_build(self) -> None:
        index = INDEX_PATH.read_text(encoding="utf-8")

        self.assertIn("Corebound is playable.", index)
        self.assertIn("playable / v0.7.0", index)
        self.assertIn("games <strong>4 games</strong>", index)
        self.assertIn('href="games/corebound/"', index)
        self.assertIn("v0.7.0 HUD Breakthrough", index)
        self.assertIn("compact overlay HUD", index)
        self.assertIn("keyboard and touch menu surfaces", index)
        self.assertIn("surface dock services", index)
        self.assertIn("richer material strata", index)
        self.assertIn("embedded ore and hazard pockets", index)
        self.assertIn("smooth drill breakthrough feedback", index)
        self.assertIn("continuous breakthrough motion", index)
        self.assertIn("Snapshots", index)
        self.assertIn('href="games/corebound/versions/0.7.0/"', index)
        self.assertIn('href="games/corebound/versions/0.6.0/"', index)
        self.assertIn('href="games/corebound/versions/0.5.0/"', index)
        self.assertIn('href="games/corebound/versions/0.4.0/"', index)
        self.assertIn('href="games/corebound/versions/0.3.0/"', index)
        self.assertIn('href="games/corebound/versions/0.2.0/"', index)
        self.assertIn("commit db07d9e81cdb", index)
        self.assertNotIn('aria-label="Corebound snapshot continuity"', index)
        self.assertNotIn("uncommitted working-tree", index)
        self.assertNotIn("No playable builds are listed yet", index)


if __name__ == "__main__":
    unittest.main()
